config/routes.rb
Rails.application.routes.draw do
  resources :contact_clubs
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/create'
  get 'clubs/index'
  get 'clubs/show'
  get 'clubs/new'
  get 'clubs/create'
  get 'clubs/edit'
  get 'clubs/update'
  get 'clubs/destroy'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 get 'cameras/show', to: 'cameras#show'
 get 'cameras/stream', to: 'cameras#stream'
  # Defines the root path route ("/")
 root 'home#index'
 resources :clubs do
  # Gestion des caméras associées à un club
  resources :cameras, only: [:show, :new, :create, :destroy] do
    member do
      post :start_recording
      post :stop_recording
    end

    # Gestion des enregistrements programmés pour une caméra
    resources :scheduled_recordings, only: [:create]
  end

  # Gestion des contacts associés à un club
  resources :contact_clubs, only: [:new, :create, :edit, :update, :destroy, :show]
end




  # Ressources liées aux events
  resources :events, only: [:index, :show, :new, :create]
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :cameras, dependent: :destroy
  has_many :contact_clubs, dependent: :destroy
  validates :name, presence: true
  validates :location, presence: true
  has_one_attached :image

  def upload_image(file)
    result = CloudflareImageUploader.upload_image(file)
    if result['success']
      update(image_id: result['result']['id'])
    else
      errors.add(:image, "Upload failed: #{result['errors']}")
      false
    end
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:start_recording, :stop_recording, :show, :edit, :update, :destroy]

  def index
    @clubs = Club.all
  end

  def show
    cloudflare_service = CloudflareService.new
    # @recordings = cloudflare_service.list_recordings(@club.live_input_id)
    @contact_clubs = @club.contact_clubs
  end



  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      if params[:club][:image].present?
        Rails.logger.info("Uploading image: #{params[:club][:image].original_filename}")
        file = params[:club][:image].tempfile
        @club.upload_image(file)
      end
      redirect_to @club, notice: 'Club created successfully.'
    else
      Rails.logger.error("Failed to save club: #{@club.errors.full_messages.join(', ')}")
      render :new
    end
  end

  def update
    Rails.logger.info("Updating club with ID: #{@club.id}")
    if @club.update(club_params)
      if params[:club][:image].present?
        Rails.logger.info("Uploading image for club: #{@club.id}")
        file = params[:club][:image].tempfile
        @club.upload_image(file)
      end
      redirect_to @club, notice: 'Club updated successfully.'
    else
      Rails.logger.error("Failed to update club: #{@club.errors.full_messages}")
      render :edit
    end
  end






  private

  def set_club
    @club = Club.find(params[:id])
  end

  def club_params
    params.require(:club).permit(
      :name,
      :description,
      :location,
      :live_input_id,
      :rtmp_url,
      :playback_url,
      :image_id,
      :adresse,
      :code_postal,
      :ville,
      :telephone,
      :latitude,
      :longitude,
      :image
    )
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Clubs#create</h1>
  <p>Find me in app/views/clubs/create.html.erb</p>
</div>

app/views/clubs/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Clubs#destroy</h1>
  <p>Find me in app/views/clubs/destroy.html.erb</p>
</div>

app/views/clubs/edit.html.erb
<h1>Créer un nouveau club</h1>

<%= form_with model: @club, local: true do |form| %>
  <div>
    <%= form.label :name, "Nom du club" %><br>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :location, "Localisation du club" %><br>
    <%= form.text_field :location, required: true %>
  </div>

  <div>
    <%= form.label :description, "Description du club" %><br>
    <%= form.text_area :description %>
  </div>

   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
  <%= form.label :adresse %>
  <%= form.text_field :adresse %>
</div>

<div class="field">
  <%= form.label :code_postal %>
  <%= form.text_field :code_postal %>
</div>

<div class="field">
  <%= form.label :ville %>
  <%= form.text_field :ville %>
</div>

<div class="field">
  <%= form.label :telephone %>
  <%= form.text_field :telephone %>
</div>

<div class="field">
  <%= form.label :latitude %>
  <%= form.number_field :latitude, step: 0.000001 %>
</div>

<div class="field">
  <%= form.label :longitude %>
  <%= form.number_field :longitude, step: 0.000001 %>
</div>


  <div>
    <%= form.submit "Créer le club" %>
  </div>
<% end %>

app/views/clubs/index.html.erb
<h1>Liste des clubs</h1>
<% @clubs.each do |club| %>
  <h2><%= link_to club.name, club_path(club) %></h2>
  <p><%= club.location %></p>
<% end %>

app/views/clubs/new.html.erb
<h1>Créer un nouveau club</h1>

<%= form_with model: @club, local: true do |form| %>
  <div>
    <%= form.label :name, "Nom du club" %><br>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :location, "Localisation du club" %><br>
    <%= form.text_field :location, required: true %>
  </div>

  <div>
    <%= form.label :description, "Description du club" %><br>
    <%= form.text_area :description %>
  </div>

   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
  <%= form.label :adresse %>
  <%= form.text_field :adresse %>
</div>

<div class="field">
  <%= form.label :code_postal %>
  <%= form.text_field :code_postal %>
</div>

<div class="field">
  <%= form.label :ville %>
  <%= form.text_field :ville %>
</div>

<div class="field">
  <%= form.label :telephone %>
  <%= form.text_field :telephone %>
</div>

<div class="field">
  <%= form.label :latitude %>
  <%= form.number_field :latitude, step: 0.000001 %>
</div>

<div class="field">
  <%= form.label :longitude %>
  <%= form.number_field :longitude, step: 0.000001 %>
</div>


  <div>
    <%= form.submit "Créer le club" %>
  </div>
<% end %>

app/views/clubs/show.html.erb
<div class="container mx-auto px-4 py-8">
  <% if @club.image.attached? %>
    <div class="flex justify-center mb-8">
      <%= image_tag @club.image, class: "rounded-lg shadow-lg max-w-full h-auto" %>
    </div>
  <% end %>

<div class="bg-white shadow-md rounded-lg p-6">
  <div class="flex items-center justify-between">
    <h1 class="text-2xl font-bold text-gray-800 mb-4"><%= @club.name %></h1>
    <%= link_to "Modifier", edit_club_path(@club), class: "text-blue-500 hover:text-blue-600 underline text-sm" %>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div>
      <p class="text-gray-600"><strong>Description :</strong> <%= @club.description %></p>
      <p class="text-gray-600"><strong>Location :</strong> <%= @club.location %></p>
      <p class="text-gray-600"><strong>Adresse :</strong> <%= @club.adresse %></p>
      <p class="text-gray-600"><strong>Code Postal :</strong> <%= @club.code_postal %></p>
      <p class="text-gray-600"><strong>Ville :</strong> <%= @club.ville %></p>
      <p class="text-gray-600"><strong>Téléphone :</strong> <%= @club.telephone %></p>
    </div>
    <div>
      <p class="text-gray-600"><strong>Latitude :</strong> <%= @club.latitude %></p>
      <p class="text-gray-600"><strong>Longitude :</strong> <%= @club.longitude %></p>
    </div>
  </div>
</div>


  <div class="bg-white shadow-md rounded-lg p-6 mt-6">
    <h2 class="text-xl font-semibold text-gray-800 mb-4">Streaming Information</h2>
    <div class="space-y-2">
      <p class="text-gray-600"><strong>Live Input ID :</strong> <%= @club.live_input_id %></p>
      <p class="text-gray-600"><strong>RTMP URL :</strong> <%= @club.rtmp_url %></p>
      <p class="text-gray-600"><strong>Playback URL :</strong> <%= @club.playback_url %></p>
      <p class="text-gray-600"><strong>Image ID :</strong> <%= @club.image_id %></p>
    </div>
  </div>

  <div class="bg-white shadow-md rounded-lg p-6 mt-6">
    <h2 class="text-xl font-semibold text-gray-800 mb-4">Dates</h2>
    <div class="space-y-2">
      <p class="text-gray-600"><strong>Créé le :</strong> <%= @club.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
      <p class="text-gray-600"><strong>Mis à jour le :</strong> <%= @club.updated_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
    </div>
  </div>

  <div class="bg-white shadow-md rounded-lg p-6 mt-6">
    <h2 class="text-xl font-semibold text-gray-800 mb-4">Caméras</h2>
    <%= link_to "Ajouter une caméra", new_club_camera_path(@club), class: "bg-blue-500 text-white py-2 px-4 rounded-lg shadow hover:bg-blue-600" %>

    <ul class="space-y-4 mt-4">
      <% @club.cameras.each do |camera| %>
        <li class="bg-gray-50 rounded-lg shadow-md p-4">
          <p class="text-gray-600"><strong>Caméra :</strong> <%= link_to camera.live_input_id, club_camera_path(@club, camera), class: "text-blue-500 hover:underline" %></p>
          <p class="text-gray-600"><strong>Flux RTMP :</strong> <%= camera.rtmp_url %></p>
          <p class="text-gray-600"><strong>Playback URL :</strong> <%= camera.playback_url %></p>
          <%= link_to "Supprimer", club_camera_path(@club, camera), method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class: "bg-red-500 text-white py-1 px-3 rounded-lg shadow hover:bg-red-600 mt-2 inline-block" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="bg-white shadow-md rounded-lg p-6 mt-6">
    <h2 class="text-xl font-semibold text-gray-800 mb-4">Contacts associés</h2>
    <%= link_to 'Ajouter un contact', new_club_contact_club_path(@club), class: 'bg-blue-500 text-white py-2 px-4 rounded-lg shadow hover:bg-blue-600 mb-4 inline-block' %>

    <% if @club.contact_clubs.present? %>
      <table class="table-auto border-collapse border border-gray-300 w-full text-left mt-4">
        <thead>
          <tr class="bg-gray-100">
            <th class="border border-gray-300 px-4 py-2">Civilité</th>
            <th class="border border-gray-300 px-4 py-2">Nom</th>
            <th class="border border-gray-300 px-4 py-2">Prénom</th>
            <th class="border border-gray-300 px-4 py-2">Téléphone</th>
            <th class="border border-gray-300 px-4 py-2">Email</th>
            <th class="border border-gray-300 px-4 py-2">Qualité</th>
            <th class="border border-gray-300 px-4 py-2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @club.contact_clubs.each do |contact| %>
            <tr class="hover:bg-gray-100">
              <td class="border border-gray-300 px-4 py-2"><%= contact.civilite %></td>
              <td class="border border-gray-300 px-4 py-2"><%= contact.nom %></td>
              <td class="border border-gray-300 px-4 py-2"><%= contact.prenom %></td>
              <td class="border border-gray-300 px-4 py-2"><%= contact.telephone %></td>
              <td class="border border-gray-300 px-4 py-2"><%= contact.mail %></td>
              <td class="border border-gray-300 px-4 py-2"><%= contact.qualite %></td>
              <td class="border border-gray-300 px-4 py-2">
                <%= link_to 'Voir', club_contact_club_path(@club, contact), class: 'text-blue-500 hover:underline' %> |
                <%= link_to 'Modifier', edit_club_contact_club_path(@club, contact), class: 'text-yellow-500 hover:underline' %> |
                <%= link_to 'Supprimer', club_contact_club_path(@club, contact), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: 'text-red-500 hover:underline' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="text-gray-600 mt-4">Aucun contact associé à ce club.</p>
    <% end %>
  </div>
</div>

app/views/clubs/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Clubs#update</h1>
  <p>Find me in app/views/clubs/update.html.erb</p>
</div>