config/routes.rb
Rails.application.routes.draw do
  resources :contact_clubs
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/create'
  get 'clubs/index'
  get 'clubs/show'
  get 'clubs/new'
  get 'clubs/create'
  get 'clubs/edit'
  get 'clubs/update'
  get 'clubs/destroy'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 get 'cameras/show', to: 'cameras#show'
 get 'cameras/stream', to: 'cameras#stream'
  # Defines the root path route ("/")
 root 'home#index'
 resources :clubs do
  # Gestion des caméras associées à un club
  resources :cameras, only: [:show, :new, :create, :destroy] do
    member do
      post :start_recording
      post :stop_recording
    end

    # Gestion des enregistrements programmés pour une caméra
    resources :scheduled_recordings, only: [:create]
  end

  # Gestion des contacts associés à un club
  resources :contact_clubs, only: [:new, :create, :edit, :update, :destroy, :show]
end




  # Ressources liées aux events
  resources :events, only: [:index, :show, :new, :create]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :club

  validates :name, presence: true
  validates :start_time, presence: true
  validates :vimeo_video_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @club = Club.find(params[:club_id])
    @events = @club.events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @club = Club.find(params[:club_id])
    @event = @club.events.build
  end

  def create
    @club = Club.find(params[:club_id])
    @event = @club.events.build(event_params)
    if @event.save
      redirect_to club_events_path(@club), notice: "L'événement a été créé avec succès."
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_time, :vimeo_video_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Events#create</h1>
  <p>Find me in app/views/events/create.html.erb</p>
</div>

app/views/events/index.html.erb
<h1>Événements de <%= @club.name %></h1>
<% @events.each do |event| %>
  <h2><%= link_to event.name, club_event_path(@club, event) %></h2>
  <p>Date : <%= event.start_time %></p>
<% end %>

app/views/events/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Events#new</h1>
  <p>Find me in app/views/events/new.html.erb</p>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p>Date : <%= @event.start_time %></p>

<div class="video-container">
  <iframe src="https://player.vimeo.com/video/<%= @event.vimeo_video_id %>" width="640" height="360" frameborder="0" allowfullscreen></iframe>
</div>