config/routes.rb
Rails.application.routes.draw do
  resources :contact_clubs
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/create'
  get 'clubs/index'
  get 'clubs/show'
  get 'clubs/new'
  get 'clubs/create'
  get 'clubs/edit'
  get 'clubs/update'
  get 'clubs/destroy'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 get 'cameras/show', to: 'cameras#show'
 get 'cameras/stream', to: 'cameras#stream'
  # Defines the root path route ("/")
 root 'home#index'
 resources :clubs do
  # Gestion des caméras associées à un club
  resources :cameras, only: [:show, :new, :create, :destroy] do
    member do
      post :start_recording
      post :stop_recording
    end

    # Gestion des enregistrements programmés pour une caméra
    resources :scheduled_recordings, only: [:create]
  end

  # Gestion des contacts associés à un club
  resources :contact_clubs, only: [:new, :create, :edit, :update, :destroy, :show]
end




  # Ressources liées aux events
  resources :events, only: [:index, :show, :new, :create]
end

app/models/camera.rb
class Camera < ApplicationRecord
  belongs_to :club
  has_many :scheduled_recordings, dependent: :destroy
  validates :live_input_id, presence: true
  validates :rtmp_url, presence: true
  validates :playback_url, presence: true
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_club
  before_action :set_camera, only: [:show, :start_recording, :stop_recording, :destroy]

  def new
    @camera = @club.cameras.new
  end

  def create
    cloudflare_service = CloudflareService.new

    # Créer un flux RTMP sur Cloudflare
    response = cloudflare_service.create_live_input(params[:camera][:name])

    if response.code == 200 && response.parsed_response["result"].present?
      input_data = response.parsed_response["result"]

      @camera = @club.cameras.new(
        live_input_id: input_data["uid"],
        rtmp_url: "#{input_data.dig("rtmps", "url")}#{input_data.dig("rtmps", "streamKey")}",
        playback_url: input_data.dig("webRTCPlayback", "url")
      )

      if @camera.save
        redirect_to @club, notice: "Caméra ajoutée avec succès."
      else
        flash[:error] = "Erreur lors de la création de la caméra : #{@camera.errors.full_messages.join(', ')}"
        render :new
      end
    else
      error_message = response.parsed_response.dig("errors") || "Erreur inconnue avec Cloudflare"
      flash[:error] = "Erreur lors de la configuration du flux Cloudflare : #{error_message}"
      render :new
    end
  end

  def show
    @camera = Camera.find(params[:id])
    cloudflare_service = CloudflareService.new

    # Récupérer les enregistrements
    @recordings = cloudflare_service.list_recordings(@camera.live_input_id)
  end



  def list_recordings_with_cache(input_id)
    Rails.cache.fetch("live_input_videos_#{input_id}", expires_in: 10.minutes, race_condition_ttl: 30) do
      list_recordings(input_id)
    end
  end


  def start_recording
    cloudflare_service = CloudflareService.new
    response = cloudflare_service.start_recording(@camera.live_input_id)

    if response.code == 200
      flash[:notice] = "L'enregistrement a démarré avec succès."
    else
      error_message = response.parsed_response.dig("errors") || "Erreur inconnue."
      flash[:alert] = "Impossible de démarrer l'enregistrement : #{error_message}"
    end

    redirect_to club_camera_path(@camera.club, @camera)
  end

  def stop_recording
    cloudflare_service = CloudflareService.new
    response = cloudflare_service.stop_recording(@camera.live_input_id)

    if response.code == 200
      flash[:notice] = "L'enregistrement a été arrêté avec succès."
    else
      error_message = response.parsed_response.dig("errors") || "Erreur inconnue."
      flash[:alert] = "Impossible d'arrêter l'enregistrement : #{error_message}"
    end

    redirect_to club_camera_path(@camera.club, @camera)
  end

  def destroy
    @camera.destroy
    redirect_to @club, notice: "Caméra supprimée avec succès."
  end

  private

  def set_club
    @club = Club.find(params[:club_id])
  end

  def set_camera
    @camera = @club.cameras.find(params[:id])
  end

  def camera_params
    params.require(:camera).permit(:name)
  end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/cameras/new.html.erb
<h1>Ajouter une caméra</h1>

<%= form_with model: [@club, @camera], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "Nom de la caméra" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Créer", class: "btn btn-primary" %>
<% end %>

app/views/cameras/show.html.erb
<h1>Caméra : <%= @camera.id %></h1>
<p>Flux RTMP : <%= @camera.rtmp_url %></p>
<p>URL de lecture : <%= @camera.playback_url %></p>
<p>live input id : <%= @camera.live_input_id %></p>

<h2>Actions d'enregistrement :</h2>
<%= form_with url: start_recording_club_camera_path(@camera.club, @camera), method: :post, class: "d-inline" do %>
  <%= button_tag "Démarrer l'enregistrement", class: "btn btn-success", data: { confirm: "Êtes-vous sûr de vouloir démarrer l'enregistrement ?" } %>
<% end %>

<%= form_with url: stop_recording_club_camera_path(@camera.club, @camera), method: :post, class: "d-inline" do %>
  <%= button_tag "Arrêter l'enregistrement", class: "btn btn-danger", data: { confirm: "Êtes-vous sûr de vouloir arrêter l'enregistrement ?" } %>
<% end %>

<h2>Flux en direct :</h2>
<div style="position: relative; padding-top: 56.25%; mb-4 ml-4">
  <iframe
    src="https://customer-e2m7xf8yvrs8kche.cloudflarestream.com/<%= @camera.live_input_id %>/iframe"
    style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;"
    allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;"
    allowfullscreen="true">
  </iframe>
</div>

<h2>Enregistrements disponibles :</h2>
<% if @recordings.present? %>
  <ul>
    <% @recordings.each do |recording| %>
      <li>
        <strong>Nom :</strong> <%= recording.dig("meta", "name") || "Sans nom" %><br>
        <strong>Créé le :</strong> <%= recording["created"] %><br>
        <strong>Durée :</strong> <%= (recording["duration"].to_f / 60).round(2) %> minutes<br>
        <div style="position: relative; padding-top: 56.25%; margin-top: 10px;">
          <iframe
            src="<%= recording["preview"] %>"
            style="border: none; position: absolute; top: 0; left: 0; height: 30%; width: 30%;"
            allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;"
            allowfullscreen="true">
          </iframe>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Aucun enregistrement disponible pour cette caméra.</p>
<% end %>

<h2>Programmer un enregistrement :</h2>
<%= form_with model: [@camera, ScheduledRecording.new], url: club_camera_scheduled_recordings_path(@camera.club, @camera), local: true do |form| %>
  <div>
    <%= form.label :start_time, "Date et heure de début" %>
    <%= form.datetime_local_field :start_time, required: true %>
  </div>
  <div>
    <%= form.label :end_time, "Date et heure de fin" %>
    <%= form.datetime_local_field :end_time, required: true %>
  </div>
  <%= form.submit "Programmer", class: "btn btn-primary" %>
<% end %>


<h2>Enregistrements programmés :</h2>
<% if @camera.scheduled_recordings.any? %>
  <ul>
    <% @camera.scheduled_recordings.each do |recording| %>
      <li>
        <strong>Début :</strong> <%= recording.start_time %><br>
        <strong>Fin :</strong> <%= recording.end_time %><br>
        <strong>Statut :</strong> <%= recording.status %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Aucun enregistrement programmé.</p>
<% end %>